server:
  port: 8084
  ssl:
    enabled: true
    key-alias: selfsigned
    key-store: classpath:keystore.jks
    key-store-type: PKCS12
    key-password: changeit
    key-store-password: changeit

spring:
  application:
    name: one-edu
  datasource:
    url: ${DB_URL:jdbc:postgresql://172.18.10.42:5432/one_edu}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 20000
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 20MB      # bitta fayl uchun maksimal hajm
      max-request-size: 20MB   # butun request hajmi (fayl + form-data)



springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs

#file:
#  storage:
#    location: /home/software/kasbiy_edu/file_storage/
#  iib_storage:
#    iib_location: /home/software/kasbiy_edu/fileStorageIIB/

jwt:
  secret: ${JWT_SECRET}

one-id:
  admin:
    client-id: ${ONEID_ADMIN_CLIENT_ID:edu_hemis}
    client-secret: ${ONEID_ADMIN_CLIENT_SECRET}
    scope: ${ONEID_ADMIN_SCOPE:hemis.uz}
    redirect-uri: ${ONEID_ADMIN_REDIRECT_URI:https://hemis.uz/api/auth/callback}
  user:
    client-id: ${ONEID_USER_CLIENT_ID:kasbiy_edu_uz}
    client-secret: ${ONEID_USER_CLIENT_SECRET}
    scope: ${ONEID_USER_SCOPE:kasbiy.edu.uz}
    redirect-uri: ${ONEID_USER_REDIRECT_URI:https://apv.edu.uz/api/public/auth/code}
